# BookVault Render Deployment Configuration
services:
  # Backend API Service
  - type: web
    name: bookvault-api
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && python -m flask db upgrade && python apply_indexes.py && gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class gthread --threads 4 --timeout 120 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 --preload --access-logfile - --error-logfile - --log-level info app:app
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: bookvault-db
          property: connectionString
      - key: AUTH_SECRET_KEY
        generateValue: true
      - key: AUTH_ALLOW_REGISTRATION
        value: true
      - key: AUTH_REQUIRE_VERIFICATION
        value: false
      - key: EXPORT_FOLDER
        value: /tmp/export_data
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FRONTEND_URL
        value: https://bookvault-frontend.vercel.app

# Database
databases:
  - name: bookvault-db
    databaseName: bookvault
    user: bookvault_user